# Generated by Django 4.0.6 on 2023-03-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='golden_coins',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='color',
        ),
    ]
