# Generated by Django 4.0.6 on 2023-03-07 00:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120, verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='test.answer', verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120, verbose_name='Вопрос')),
                ('num_of_right_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Номер правильного ответа')),
                ('answers', models.ManyToManyField(related_name='answers', through='test.AnswerAmount', to='test.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название теста')),
                ('min_right_answers', models.IntegerField(verbose_name='Минимальное количество ответов для прохождение теста')),
                ('reward', models.PositiveIntegerField(verbose_name='Награда')),
                ('questions', models.ManyToManyField(related_name='questions', to='test.question')),
            ],
        ),
        migrations.CreateModel(
            name='DoneTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donetests', to='test.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdonetests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answeramount',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='test.question', verbose_name='Вопрос'),
        ),
    ]
